version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_whatsapp
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_USER
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
    volumes:
      - mongodb_whatsapp_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_whatsapp_data:/data

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_whatsapp_data:/data
    ports:
      - "9000:9000"
      - "9090:9090"
    command: server /data --console-address ":9090"

volumes:
  mongodb_whatsapp_data:
  redis_whatsapp_data:
  minio_whatsapp_data: