"""add uniqueness on users_chats table

Revision ID: 9ffe0c18c319
Revises: 685e6da7e87c
Create Date: 2024-07-29 10:57:28.639700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ffe0c18c319'
down_revision: Union[str, None] = '685e6da7e87c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_chat', 'user_chats', ['user_id', 'chat_id'])
    op.drop_constraint('user_chats_chat_id_fkey', 'user_chats', type_='foreignkey')
    op.create_foreign_key(None, 'user_chats', 'chats', ['chat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_chats', type_='foreignkey')
    op.create_foreign_key('user_chats_chat_id_fkey', 'user_chats', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_user_chat', 'user_chats', type_='unique')
    # ### end Alembic commands ###
